services:
  postgresql:
    image: postgres@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722 # 18.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: python_template
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d:ro

volumes:
  postgresql:
